### PR TITLE
[ENH]: DICOM to NIFTI BIDS conversion with Heudiconv

### PR DESCRIPTION
**Pull request by alexpron**
Adding [datalad](https://github.com/datalad) support within _shanoir2bids.py_ script relying on [heudiconv ](https://github.com/nipy/heudiconv) software.

Tried to reproduce as far as possible the current usage of the _shanoir2bids.py_ script from _configuration.json_ file

+ **DICOM download only** from Shanoir instance (regression)
+ removed automri format output (regression)
+ BIDS mapping generated from the result of the solr search to handle case where regex like terms were passed into .json file
+ BIDS conversion is performed at the subject level (session if longitudinal)
+ Modified a bit dcm2niix options so that it matches the --dcmconfig option .json file 
(keys are attributes to DCM2NIIX nipype class)
+ DICOM to NIFTI BIDS conversion, both DICOM and NIFTI are stored into datalad datasets (sourcedata, rawdata)

TODO:
- [x] check bids metadata generated 
- [x] add studyname in dl_dir using locator ? 
- [x] better handle temporary directory
- [x] add conversion directly from zip files
- [x] write Heudiconv heuristic to handle conversion into automri format 
- [x] define what to do when chosen outputs are not BIDS compliant (e.g. sub-\d\d--\d\d)

### CODE REVIEW

**Comment by alexpron** [comment]
some bids compliance errors with default dcm2niix options used:
image

**Comment by alexpron** [comment]
- bids compliance problem was solved using -ba option of dcm2niix if -ba should not be applyied check field by field
-  bids validator was run on the obtained files and current filenames used should be modified in the configuration file
-  some characters are forbidden in subject_id such as - hence XX-XX is not a BIDS compliant name 
-  in order to keep this name use the non bids formatting and manually recreats ontology within the heuristic file ?

**Comment by alexpron** [comment]
tar or tar.gz files only are correctly handled by heudiconv (.zip files currently not supported)

**Comment by alexpron** [comment]
- [ ] include debug mode with directory kept i.e. switch to manually specified directories and manual delete if required
- [ ] remove {subject_session_dir} prefix in case of automri heuristic
- [ ] remove {subject_session_prefix} in case of automri heuristic
- [ ] if not working implement simple BIDS to automri mappping

**Optional**
>  to be done in a dedicated PR
- [ ] solr query enhancement : concatenate all queries into a single one

**Comment by alexpron** [comment]
- include debug mode with directory kept i.e. switch to manually specified directories and manual delete if required
 by default temporary directory are deleted after context execution. 
 The delete keyword allowing to keep the directory is only available in python 3.12 which is too restrictive currently
 Hence temporary directory mechanism will be replaced by directories and conditional manual deletion

**Comment by alexpron** [comment]
An heuristic covering automri conversion was included into few commits. However it was decided to focus on BIDS conversion only. An script belonging to a different repo (bids_to_automri) was written as well as a PR to evaluate the time needed to go from automri to BIDS ontology as the new organisation of the automri code.

**Comment by alexpron** [comment]
request optimisation has been started but not implemented in the end as it would require to rethink the whole configuration file usage (e.g. using a proper heuristic for each study instead of direct mapping)

**Comment by alexpron** [comment]
+ added basic check of BIDS path generated  relying on the configuration file (bids_validator)
+ overwrite mode was set to True (data are overwrite and then datalad handles their integration or not if they exist already)
+ linting and improving checks

**Comment by alexpron** [comment]
- [ ] write documentation about shanoir2bids_heudiconv of the README file
- [ ] add deprecation warning for shanoir2bids ?

**Comment by quentinduche** [comment]
`datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false ls-files --stage -z -- .heudiconv' failed with exitcode 128`

**Comment by alexpron** [comment]
Clean Installation instructions For Debug
```
conda create -n test python=3.11
conda activate test 
conda install python-dotenv
conda install -c conda-forge heudiconv pybids datalad git-annex=*=alldep*
```

**Pull request merged**
