### PR TITLE
BIDS 1.9.0 compatibility of NIFTI data

### PR DESCRIPTION
**Pull request by alexpron**
Few renaming based on examples configuration.json files to see what is possible to modify to insure BIDS 1.9.0 compatibility.

### CODE REVIEW

**Comment by alexpron** [comment]
image

Ouput of BIDS validator on BIDS mapping generated using EMISEP  configuration file
- brain and spinalCord subdirectories are not compliant --> how to encode bodypart/sample ?
- suffix of filenames is not recognized as there is an _ splitting character

**Comment by alexpron** [comment]
encoding bodypart imaged is not defined by BIDS specification. In https://github.com/courtois-neuromod/ds_prep/blob/main/mri/convert/heuristics_unf.py a bodypart key bp- is added but this is also not BIDS compliant. Ask the question to neurostars

**Comment by alexpron** [comment]
https://neurostars.org/t/bids-for-spinal-cord/29143

**Review by quentinduche — APPROVED** [review]
This is ok

**Review by alexpron — COMMENTED** [review]
line 10 has wrong phase encoding direction (AP --> PA)

**Pull request merged**
